### ISSUE TITLE
[버그] . 가 잘못된 위치에 있습니다.

### ISSUE THREAD

**Issue by editionc18** [ArpaAP/mollang#2]
### 버그 설명
Readme에 있는
```
몰??
몰???
몰!
몰.???
몰루
```

코드를 입력 시 12가 출력된다고 나와있는데 다음과 같이 출력됩니다.

```
4
[3:13] . 가 잘못된 위치에 있습니다.
종료 코드: 0
```

### 예상한 동작
12가 출력되어야 합니다.

### 실행 환경:
 - 실행 환경: 웹 인터프리터
 - 몰랭 언어 버전: 1.1

**Comment by dacoonkr** [comment]
JS인터프리터는 현재 버그가 많은 관계로, 현재 웹 인터프리터는 v1.1문법을 지원하고 있지 않습니다. 빠른 시일 내로 업데이트하도록 하겠습니다.

**Comment by ArpaAP** [comment]
현재 웹 인터프리터에서 몰랭 1.1 구현체 지원을 추가하여 정상적인 실행이 가능합니다.
