### ISSUE TITLE
[버그] 루? 입력 오류

### ISSUE THREAD

**Issue by kndlr** [ArpaAP/mollang#3]
### 버그 설명
`루?` 변수 대입 시, 출력을 통해 정상적으로 대입되었다는 것을 확인할 수 있지만, UNDEFINED_VARIABLE(-1) 오류 발생

### 실행 환경 (아래 양식을 채워주세요. 해당되지 않는 부분은 입력하지 않아도 됩니다.):
 - 몰랭 언어 버전: 1.1
 - 구현체 언어: C++, JS
 - 구현체 버전: 1.1

**Comment by dacoonkr** [comment]
C++문제 해결되었습니다

**Comment by kndlr** [comment]
https://github.com/ArpaAP/mollang/commit/355598151d00ceb4ff9ce1a3bddf92551b39488e
